### ISSUE TITLE
[BUG] Active Modules plugin negatively impacts canvas text cards' rendering

### ISSUE THREAD

**Issue by stef-rausch** [polyipseity/obsidian-modules#2]
With the `Modules` plugin disabled, a canvas renders text cards as expected.

_**Enabling the plugin, a canvas only displays the cards' border and background colour, i.e., text is not rendered.**_ All other objects (notes and any media) are not affected.

What does `Modules` patch to have the above-stated impact on canvas?

SYSTEM INFO:
	Obsidian version: v1.4.4
	Installer version: v1.3.7

OPERATING SYSTEM:
        Edition	Windows 11 Home Single Language
        Version	22H2
        Installed on	‎2023-‎02-‎23
        OS build	22621.2215
        Experience	Windows Feature Experience Pack 1000.22662.1000.0

**Comment by polyipseity** [comment]
Fixed in 663d9eb10fb54c80a82bc25b307977293e370d69. Deleting the plugin and redownloading it via BRAT should work for now before I release it.

**Comment by stef-rausch** [comment]
I can confirm -- thank you!

**Comment by polyipseity** [comment]
Released in [2.1.0](https://github.com/polyipseity/obsidian-modules/releases/2.1.0).
