### ISSUE TITLE
Question: Can we create user dialogs with this?

### ISSUE THREAD

**Issue by stecydube** [polyipseity/obsidian-modules#6]
Sorry to raise an issue as this repo does not have a discussion area.

Is it possible to create a class that extends Modal and being able to use it somewhere?

Thanks 😀

**Comment by polyipseity** [comment]
Turn on "Expose internal modules" in plugin settings and use the following code:

```JavaScript
const { Modal } = await require.import("obsidian");
export class MyModal extends Modal {
  // custom modal code
}
```

Then you can use it:

```JavaScript
const { MyModal } = await require.import("path/to/script.js");
new MyModal(app).open();
```

For future references, `require("obsidian")` will return an object containing everything in [`obsidian.d.ts`](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts). You just need to access them by name, like `require("obsidian").Modal` for `Modal`.

**Comment by stecydube** [comment]
Awesome. Thanks!
